### ISSUE TITLE
app hang, freeze after switching the server

### ISSUE THREAD

**Issue by marcel263** [mozilla-mobile/mozilla-vpn-client#9548]
**Describe the bug**

**VPN version:**
2.21.0

**Affected Platforms:**
Android 13 OneUI 5.1

**Steps to reproduce:**
   VPN set to auto connect in Android settings.
Boot device, VPN auto connecting.
Launch Mozilla VPN to change the location
switch apps
Launch again Mozilla VPN

**Actual result:**
The app displays a white or black screen.
It has to be force closed through App settings.
After a few minutes, Android overlays on display "app not responding" for Mozilla VPN.

**Additional notes:**
 [MozillaVPN_Logs_2024-11-08-12-11-18.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/15292964/MozillaVPN_Logs_2024-11-08-12-11-18.txt)

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

22% of users are on Android 13. Valentina Virlics do you have any device on Android 13 to test this?

**Comment by data-sync-user** [comment]
➤ Santiago Andrigo commented:

Addendum: Valentina also tried on Android 10 (Pixel) and 14 (Samsung) and can’t replicate either.
We don’t have the precise combination reported here (Android 13, Samsung), alas.

**Comment by albionx** [comment]
@marcel263 Would you mind trying with the latest version please? We just pushed version 2.22 to the Play Store yesterday and it will slowly ramp up (reaching 100% by next week).

Once you have it, I would also recommend using one of the new features we launched in the new version: Settings -> Help -> Reset VPN. This will log you out and clear a bunch of things, which might do the trick in case your installation got itself on some weird setup. More info here: https://support.mozilla.org/en-US/kb/how-remove-mozilla-vpn-app-data-your-device

**Comment by marcel263** [comment]
> @marcel263 Would you mind trying with the latest version please? We just pushed version 2.22 to the Play Store yesterday and it will slowly ramp up (reaching 100% by next week).
> 
> Once you have it, I would also recommend using one of the new features we launched in the new version: Settings -> Help -> Reset VPN. This will log you out and clear a bunch of things, which might do the trick in case your installation got itself on some weird setup. More info here: https://support.mozilla.org/en-US/kb/how-remove-mozilla-vpn-app-data-your-device

Dear, after updating to 2.22.0, the app always freezes after just reopening it, worsening the issue.
[MozillaVPN_Logs_2024-21-15-8-21-26.txt](https://github.com/mozilla-mobile/mozilla-vpn-client/files/15317042/MozillaVPN_Logs_2024-21-15-8-21-26.txt)

attached is the log after triggering, and force-killing the bug a few times.

**Comment by marcel263** [comment]
The app is now 2.22.0 and freshly installed.

After turning on wifi and connecting it, lte is cut off. Now, Mozilla VPN, which was already running, is frozen again after invoking its UI. The app appears frozen.

**Comment by marcel263** [comment]
> Thanks @marcel263 can you confirm that you indeed used the 'Reset VPN' prior to the last test?

hello,
yes, first the in-app reset procedure from Help. Afterwards, while going through the setup, it froze after reaching another app and switching back for password entry.

Then, I reinstalled the app, bypassing a clearing of data and cache in Android. As described it was still happening afterwards.

Currently it stopped but may trigger at any time.

Also, after reinstalling, the VPN started cutting out with the screen off for a few minutes. Turning on the screen would resume it, e.g. a streaming app would resume playing (no other changes then reinstalling Mozilla VPN). This issue was fixed by setting Mozilla VPN's battery mode to "unrestricted".

**Comment by marcel263** [comment]
confirming the bug still occurs
